# ======================================================
# HyprMax Animations
# ======================================================

animations {
    enabled = yes

    bezier = easeOut,0.25,1,0.5,1
    bezier = easeInOut,0.87,0,0.13,1

    animation = windows,1,7,easeOut
    animation = windowsOut,1,7,easeInOut
    animation = border,1,10,default
    animation = fade,1,7,default
    animation = workspaces,1,8,easeOut
}
