# ======================================================
# HyprMax Autostart
# ======================================================

exec-once = waybar
exec-once = swaync
exec-once = swww-daemon
exec-once = nm-applet
exec-once = blueman-applet
exec-once = hypridle
exec-once = hyprpaper

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1
