# ======================================================
# HyprMax - Main Configuration
# Author: Prem Kale
# Version: 0.1.0
# ======================================================

# Variables
source = ~/.config/hypr/variables.conf

# Hardware
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf

# Environment
source = ~/.config/hypr/env.conf

# Appearance
source = ~/.config/hypr/decorations.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/windowrules.conf

# Startup
source = ~/.config/hypr/autostart.conf

# Keybindings
source = ~/.config/hypr/keybindings.conf
