# ======================================================
# HyprMax Variables
# Version: 0.1.0
# ======================================================

# -----------------------------
# Applications
# -----------------------------
$terminal = kitty
$fileManager = dolphin
$browser = google-chrome-stable
$menu = walker

# -----------------------------
# Appearance
# -----------------------------
$mainMod = SUPER

# Layout
$gapsIn = 6
$gapsOut = 12
$borderSize = 2
$rounding = 12

# Cursor
$cursorSize = 24

# Animation Speed
$animationSpeed = 1.0

# Theme
$theme = catppuccin-mocha

# Wallpaper
$wallpaper = ~/.config/hypr/wallpapers/default.jpg
